branch-defaults:
  master:
    environment: prod
    group_suffix: null
global:
  application_name: pillar-api
  branch: null
  default_ec2_keyname: null
  default_platform: (BETA) PHP 7.4 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
